feat: добавил всё
Kalabass/Web-bee-hacker-news pull request #1
Opened 2024-07-30 14:56 UTC by Kalabass

2024-07-30 18:14 UTC, kseniakap approved these changes

2024-07-30 18:14 UTC, kseniakap commented on client/src/shared/store/useCommentsStore.ts
> +export const useCommentStore = create<CommentState>()(
Сообщение "The declaration was marked as deprecated here."
Используй такой импорт: import { create } from 'zustand'

2024-07-30 18:14 UTC, kseniakap commented on client/src/pages/main/ui/Page.tsx
> +          <RefetchButton text='Refresh Articles' onClick={() => refetch()} />
При нажатии на кнопку refetch нет никого сообщения о том, что данные обновились.
(У обычного пользователя будет складываться впечатление, что кнопка нерабочая)

2024-07-30 18:14 UTC, kseniakap commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +          <Link to={'http://localhost:3000/'}>HackerNews</Link>
Нет необходимости прописывать полностью url, достаточно прописать только "/"

2024-07-30 18:14 UTC, kseniakap commented on client/src/entities/article/ui/Card.tsx
> +        <Stack direction='row' spacing={1}>
Немного поехало 
![image](https://github.com/user-attachments/assets/72db11d4-022e-48d0-ba6c-f549c2d23640)

2024-07-30 18:14 UTC, kseniakap commented on client/src/pages/article-page/ui/Page.tsx
> +            onClick={() => console.log('hello =)')}
Может делать повторный запрос на получение данных страницы при нажатии?

2024-07-30 18:14 UTC, kseniakap commented on client/src/pages/index.tsx
> +      <Route path='/article/:id' element={<ArticlePage />} />
Думаю, стоит обработать тот случай, если пользователь перейдет по несуществующему адресу

2024-07-30 18:14 UTC, kseniakap commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +import { FC, ReactNode } from 'react';
В React правильный порядок импортов выглядит следующим образом:
1. Импорты из стандартной библиотеки JavaScript (например, `react`, `react-dom`).
2. Импорты из сторонних библиотек (например, `redux`, `axios`).
3. Импорты из проекта (внутренние импорты). 
```javascript
import { FC, ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { AppBar, Toolbar, Typography, styled } from '@mui/material';
```

2024-07-30 18:14 UTC, kseniakap commented on client/src/widgets/article-content/ui/ArticleContent.tsx
> +        </>
Предлагаю вынести в отдельный компонент, чтобы не загромождать

2024-07-30 18:14 UTC, kseniakap commented on server/src/articles/articles.service.ts
> +    const BASE_URL = 'https://api.hnpwa.com/v0/newest';
Стоит вынести константы из функции по причине:
Если функция вызывается многократно, константа будет создаваться заново каждый раз (а зачем нам это нужно?)
Предлагаю вынести как const BASE_URL = 'https://api.hnpwa.com/v0/ и использовать дальше во всех функциях ниже

2024-07-30 18:14 UTC, kseniakap commented on server/src/articles/articles.service.ts
> +    allNews = allNews.slice(0, 100);
Более компактный вариант:

```javascript
return allNews.slice(0, 100);
```

2024-07-31 08:39 UTC, G00syara commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +          <Link to={'http://localhost:3000/'}>HackerNews</Link>
Если у меня порт не 3000, то что будет?)

2024-07-31 08:42 UTC, G00syara commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +import { FC, ReactNode } from 'react';
Это зависит от настроек `prettier`, как такового правильного порядка не существует, это от проекта к проекту может меняться, так что порядок импортов не важен

2024-07-31 10:35 UTC, aidagalimova commented on client/src/entities/article/ui/Card.tsx
> +          </InfoTypography>
{' '} лишнее

2024-07-31 10:38 UTC, aidagalimova commented on client/src/entities/comment/ui/Card.tsx
> +          {user}{' '}
{' '}

2024-07-31 10:38 UTC, aidagalimova commented on client/src/widgets/article-content/ui/ArticleContent.tsx
> +            {data.comments_count}{' '}
{' '}

2024-07-31 10:40 UTC, aidagalimova commented on client/src/shared/ui/RefetchButton.tsx
> +  const onCLickHandler = () => {
L - прописная

2024-07-31 10:52 UTC, aidagalimova commented on client/src/shared/model/article-interfaces/interfaces.ts
> +  domain?: string;
Так как у тебя есть бек, возможно прямо там стоит отфильтровать значения, которые на фронте не будут нужны

2024-07-31 10:53 UTC, aidagalimova commented on client/src/entities/article/ui/Card.tsx
> +            {points} {points == 1 ? 'point' : 'points'}{' '}
нестрогое равенство

2024-07-31 11:05 UTC, aidagalimova commented on client/src/pages/article-page/ui/Page.tsx
> +          <ArticleContent id={+id!} />
если передать строку: 
![изображение](https://github.com/user-attachments/assets/973b1150-93a3-4a37-97df-bb0a98f4bdf7)

2024-07-31 11:07 UTC, aidagalimova commented
![изображение](https://github.com/user-attachments/assets/d14739f7-9619-4c52-89fb-7fbe65b1eee7)
В конце страниц отображается ;

2024-07-31 13:21 UTC, kseniakap commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +import { FC, ReactNode } from 'react';
Аааа, не знала, спасибо, теперь буду знать

2024-07-31 15:15 UTC, Kalabass commented on client/src/shared/model/article-interfaces/interfaces.ts
> +  domain?: string;
> Так как у тебя есть бек, возможно прямо там стоит отфильтровать значения, которые на фронте не будут нужны

Согласен, так правильнее. 
Но я сделано это для удобства, чтобы если в процессе разработки что-то понадобилось дополнительное взять или наоборот отказать от какого-то поля, то изменить надо было бы только один интерфейс на фронте, а не в двух местах. 
Не очень хорошо, но, думаю, не критично

2024-07-31 15:45 UTC, aidagalimova approved these changes

2024-08-02 07:07 UTC, al-revenko requested changes

2024-08-02 07:07 UTC, al-revenko commented on client/index.html
> +    <title>Vite + React + TS</title>
Измени title

2024-08-02 07:07 UTC, al-revenko commented on client/env.d.ts
Эти типы вроде как лишние. Я не нашёл места в проекте, где используются значения из окружения

2024-08-02 07:07 UTC, al-revenko commented on docker-compose.yaml
> +version: '3.8'
Удали эту строчку. Из-за неё Docker ругается - `version is obsolete`. 
Погуглил и вроде как строчка "version" уже устарела и её не надо указывать

2024-08-02 07:07 UTC, al-revenko commented on client/src/entities/article/ui/Card.tsx
> +        <Stack direction='row' spacing={1} alignItems='center'>
Куратор мне уже дал по жопе из-за этого. Цитата:

> Если есть стилизованный компонент, стоит все стили указывать внутри styled. Не стоит часть стилей писать в аргументы, часть под styled - G00syara 

Поэтому постарайся такие вещи убрать из кода

2024-08-02 07:07 UTC, al-revenko commented on client/src/entities/comment/ui/Card.tsx
> +        <UserTypography custom_color='text.primary'>{user}</UserTypography>
Тут тоже вынеси стили в styled

2024-08-02 07:07 UTC, al-revenko commented on client/src/shared/ui/RefetchButton.tsx
> +      color='inherit'
Если получится, то лучше color перенести непосредственно в стили StyledButton

2024-08-02 07:07 UTC, al-revenko commented on client/src/vite-env.d.ts
Эти типы env вроде как тоже не используются

2024-08-02 07:07 UTC, al-revenko commented on client/src/entities/article/ui/Card.tsx
> +        <Stack direction='row' spacing={1} alignItems='center'>
Вынеси в styled

2024-08-02 07:07 UTC, al-revenko commented on client/src/entities/comment/helpers/useComments.ts
> +    refetchInterval: 60000,
Это значение интервала лучше вынести в отдельную константу.  Оно же ещё и в useArticles используется

2024-08-02 07:07 UTC, al-revenko commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +        sx={{ gap: '8px', display: 'flex', justifyContent: 'space-between' }}
Вынеси в styled

2024-08-02 07:07 UTC, al-revenko commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +        <StyledTypography fontWeight={800}>
это тоже

2024-08-02 07:07 UTC, al-revenko commented on client/vite-env.d.ts
Брат мой во христе, тебе зачем целых 3 (!) d.ts файлов для типизации окружения которые не используются? К тому же этот файл дублирует файл vite-env из src

2024-08-02 07:07 UTC, al-revenko commented on server/src/app.module.ts
Я чота подозреваю что этот модуль лишний с его Hello World контроллером и сервисом)

2024-08-02 07:07 UTC, al-revenko commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +export const NavBar: FC<NavBarProps> = ({ children }) => {
NavBar по-хорошему надо ограничить по ширине чтобы на больших экранах инпуты не разъехались слишком далеко. Короч ограничь его так же как и основной контент страниц

2024-08-02 07:21 UTC, al-revenko commented on client/src/pages/index.tsx
> +    </Routes>
Дополню: такой способ указывания роутов в react-router-dom v6 уже вроде как не рекомендуется. Укажи их лучше так https://reactrouter.com/en/main/routers/create-browser-router

2024-08-02 13:50 UTC, G00syara commented
Называй папки через `pascalCase`, а не `snake-case`

2024-08-02 13:54 UTC, G00syara commented
Если перейти по не существующему артиклу, есть возможность обновить комментарии, задизейбли её, если дата не пришла

2024-08-02 14:33 UTC, G00syara requested changes

2024-08-02 14:33 UTC, G00syara commented on server/src/articles/articles.service.ts
> +  private BASE_URL = 'https://api.hnpwa.com/v0';
В .env.example

2024-08-02 14:33 UTC, G00syara commented on client/env.d.ts
Если у тебя локально есть `env`, то должен быть `env.example`, в котором находятся значения, которые я сам себе могу в .env вставить

2024-08-02 14:33 UTC, G00syara commented on client/src/app/index.tsx
> +    withRouter(() => {
Почему просто не обернул через компонент в созданный `muiTheme`, а сделал так? Лучше сделать отдельные Provider и обернуть в них компоненты, а не один общий

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/article/index.ts
Что это и зачем?

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/article/model/interfaces.ts
Не совсем понимаю почему такое название файла, он находится в модели, внутри него интерфейс с пропами для артикла. Лучше обозвать папку `types`, внутри папки указать, что это `article`

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/article/ui/Card.tsx
> +      to={`article/${id}`}
Вынеси пути в константы

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/article/ui/Card.tsx
> +        <TitleTypography as='h2'>{title}</TitleTypography>
Зачем здесь `as`?

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/comment/ui/Card.tsx
> +        width: `${level === 0 ? '100%' : '98%'}`,
Что за лютый и непонятный костыль?

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/article/ui/Card.tsx
> +export const ArticleCard: FC<ArticleCardProps> = ({
Хороший тон, когда файл называется точно так же как экспортируемый компонент, т.к. в данном случае надо переименовать Card ->  ArticleCard, у тебя такая проблема ещё есть в нескольких местах, исправь и там

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/comment/index.ts
Зачем?

2024-08-02 14:33 UTC, G00syara commented on client/src/features/articles-list/index.ts
?

2024-08-02 14:33 UTC, G00syara commented on client/src/features/articles-list/index.ts
С остальными такими же файлами аналогичный вопрос, зачем они?

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/comment/ui/Card.tsx
> +        <InfoTypography>{time_ago}</InfoTypography>
Преобразовывай данные к `PascalCase` формату, это относится ко всем данным в `snake_case`

2024-08-02 14:33 UTC, G00syara commented on client/src/features/comment-tree/ui/CommentTree.tsx
> +
Пустая строка

2024-08-02 14:33 UTC, G00syara commented on client/src/shared/api/axios-instance.ts
> +  baseURL: 'http://localhost:5252/',
В `env`

2024-08-02 14:33 UTC, G00syara commented on client/src/shared/model/article-interfaces/interfaces.ts
> +  domain?: string;
Лучше перенести логику обработки данных на бэк и уже с бэка получать данные в том виде в котором они должны прийти, не везде так, но это правильнее. Цена преобразования данных на фронте гораздо больше чем на бэке

2024-08-02 14:33 UTC, G00syara commented on client/src/entities/article/model/interfaces.ts
В других папках аналогично

2024-08-02 14:33 UTC, G00syara commented on client/src/shared/ui/NotFoundBox.tsx
> +export interface NotFoundBox {
Если придерживаешься того, что у тебя типы находятся не в компоненте, то тогда нужно вынести в отдельный файл

2024-08-02 14:33 UTC, G00syara commented on client/vite.config.ts
> +    port: 3000,
Доставать порт надо из env и делать альтернативный порт, если его нет

2024-08-02 14:33 UTC, G00syara commented on server/src/app.module.ts
> +  providers: [AppService],
Оставь только импорты, всё остальное снести

2024-08-02 14:33 UTC, G00syara commented on server/src/articles/articles.controller.spec.ts
Зачем? Можно же его снести, с остальными `spec` аналогично

2024-08-02 14:33 UTC, G00syara commented on server/src/articles/articles.service.ts
> +  }
Тебе же обязательно запускать каждый запрос последовательно, запусти асинхронно, а потом обреж данные до 100

2024-08-06 14:54 UTC, G00syara commented on client/src/entities/article/index.ts
Хочется слышать ответ на такие вопросы

2024-08-06 16:36 UTC, Kalabass commented on client/src/entities/comment/ui/Card.tsx
> +        width: `${level === 0 ? '100%' : '98%'}`,
Чтобы комменты первого уровня отображались в полную ширину, а следующие уменьшались

2024-08-06 16:36 UTC, Kalabass commented on client/src/entities/article/index.ts
Хотел попробовать структуру FSD, там вроде как так принято

2024-08-06 16:49 UTC, Kalabass commented on client/src/entities/article/index.ts
Сорри, почему-то решил, что сначала исправить, код, а потом просто ответить на вопрос будет хорошим решением 💀 
My bad

2024-08-06 19:53 UTC, sspopkov requested changes

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +      console.error('error fetching articles', e);
Обработка ошибки дублируется несколько раз, используй какой-нибудь `handleError`

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +    return new Date(unixTimestamp * 1000).toLocaleString();
Магические числа 1000, 100 не используем, выноси в константы

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +      'https://api.hnpwa.com/v0';
Где константы для адресов?

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +      const response = await firstValueFrom(
Дублирование кода на 62 строке

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +      const transformComments = (comments: Item[]): CommentData[] => {
Вынеси в отдельную функцию для лучшей читаемости, а то очень длинно
```
  private transformComments(comments: Item[]): CommentData[] {
    return comments.map(this.transformComment.bind(this));
  }
  
  private transformComment(comment: Item): CommentData {
    ... comments: comments ? this.transformComments(comments) : [] ...
  }
```

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +        this.httpService.get<Item>(`${this.API_BASE_URL}/item/${id}.json`),
Тоже дублируется, вынеси в отдельную переменную

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.service.ts
> +        .slice(0, 100)
Константы

2024-08-06 19:53 UTC, sspopkov commented on server/test/app.e2e-spec.ts
Важно завершать приложение в `afterAll`

2024-08-06 19:53 UTC, sspopkov commented on server/test/app.e2e-spec.ts
> +  beforeEach(async () => {
`beforeAll` быстрее `beforeEach`, лучше его

2024-08-06 19:53 UTC, sspopkov commented on server/src/main.ts
Обрабатывай ошибку и сообщай какой-нибудь `Error starting the application`. Хорошей практикой является логирование URL, на котором стартует проект

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/interfaces/interfaces.ts
> +  points?: number | null;
Здесь `points` и `user` опциональные, а в `Item` нет

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.controller.ts
> +  @Get('/comments/:id')
Слеш перед `id` не нужен

2024-08-06 19:53 UTC, sspopkov commented on server/src/articles/articles.controller.ts
> +    return this.articlesService.getOne(+id);
Вместо js-ного `+` используй декораторы - `ParseIntPipe`

2024-08-06 19:53 UTC, sspopkov commented on client/vite.config.ts
> +import react from '@vitejs/plugin-react';
Строчная буква у `react`

2024-08-06 19:53 UTC, sspopkov commented on client/vite.config.ts
> +      port: +env.VITE_PORT || 3000,
Лучше не использовать унарные операторы, `Number` будет более очевидным и читаемым

2024-08-06 19:53 UTC, sspopkov commented on client/src/widgets/nav-bar/ui/NavBar.tsx
> +  gap: 8px;
Используй `theme.spacing`, более консистентно с темой будет

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/ui/Typography.tsx
> +  shouldForwardProp: (prop) => prop !== 'custom_color',
Здесь `custom_color`, а ранее `CustomColor`

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/ui/Typography.tsx
> +  color: CustomColor ? CustomColor : theme.palette.primary.main,
Тернарник тут лишний, `||` хватит

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/ui/Typography.tsx
> +  variant: 'body2',
В стилизованном компоненте `variant` не будет работать же

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/ui/RefetchButton.tsx
> +    refetch();
Асинхронная операция без `await`, потенциальные гонки могут возникнуть, нет обработки ошибки

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/ui/NotFoundBox.tsx
> +      display='flex'
Встроенные стили не в кодстайле со `styled-components`

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/ui/Loader.tsx
> +      <CircularProgress size={200} />
`size` захардкожен. 200 большое довольно, на мобильных устройствах корректно отображается?

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/api/articleService.ts
> +    return await instance.get<ArticleData[]>('articles');
Нет обработки ошибок

2024-08-06 19:53 UTC, sspopkov commented on client/src/shared/api/articleService.ts
> +  async getOne(id: number) {
Типы возвращаемых значений не описаны

2024-08-06 19:53 UTC, sspopkov commented on client/src/pages/notFound/ui/NotFoundPage.tsx
> +export const NotFoundPage: FC = () => {
Компонент без пропсов описываем типом `React.VFC`

2024-08-06 19:53 UTC, sspopkov commented on client/src/pages/main/ui/MainPage.tsx
> +        children={<RefetchButton query={useArticles()} entity='articles' />}
Стандартным подходом будет вложенный компонент без использования `children`

2024-08-06 19:53 UTC, sspopkov commented on client/src/pages/main/ui/MainPage.tsx
> +  const articlesQuery = useArticles();
`useArticles()` дважды вызывается. Вызывай один раз и передавай в нужные компоненты

2024-08-06 19:53 UTC, sspopkov commented on client/src/pages/main/ui/MainPage.tsx
> +export const MainPage: FC = () => {
Нет пропсов, лучше `React.VFC`

2024-08-06 19:53 UTC, sspopkov commented on client/src/pages/article/ui/ArticlePage.tsx
> +        children={
Не используем `children`

2024-08-06 19:53 UTC, sspopkov commented on client/src/pages/article/ui/ArticlePage.tsx
> +export const ArticlePage: FC = () => {
`VFC`

2024-08-06 19:53 UTC, sspopkov commented on client/src/features/commentTree/ui/CommentTree.tsx
> +            commentTree={<CommentTree comments={comment.comments} />}
Оптимизировать рекурсивный рендеринг можно, добавить проверку на то, что комментариев больше нуля, только тогда рендерить новое `CommentTree`

2024-08-06 19:53 UTC, sspopkov commented on client/src/entities/comment/ui/CommentCard.tsx
> +        <StyledTypography dangerouslySetInnerHTML={{ __html: content }} />
`dangerouslySetInnerHTML` экранируем с `DOMPurify`, это небезопасный код

2024-08-07 05:46 UTC, al-revenko requested changes

2024-08-07 05:46 UTC, al-revenko commented on client/src/entities/article/ui/ArticleCard.tsx
> +          <Stack direction='row' spacing={1} alignItems='center'>
`direction='row' spacing={1} alignItems='center'` - тоже надо в styled вынести)

2024-08-07 15:08 UTC, Kalabass commented on server/src/articles/interfaces/interfaces.ts
> +  points?: number | null;
это типизация из доки апихи https://github.com/tastejs/hacker-news-pwas/blob/master/docs/api.md

2024-08-07 15:14 UTC, Kalabass commented on server/src/articles/articles.controller.ts
> +  @Get('/comments/:id')
без него не работает, но в доке не нашел, там только пример с  :id без строки перед ним  https://docs.nestjs.com/controllers#routing

2024-08-07 15:15 UTC, Kalabass commented on client/src/shared/ui/Loader.tsx
> +      <CircularProgress size={200} />
Захардкожен, но отображается корректно

2024-08-07 15:20 UTC, Kalabass commented on client/src/pages/notFound/ui/NotFoundPage.tsx
> +export const NotFoundPage: FC = () => {
'VFC' is deprecated. ts(6385)
index.d.ts(1188, 8): The declaration was marked as deprecated here.
(alias) type VFC<P = {}> = React.VoidFunctionComponent<P>
import VFC
@deprecated — Equivalent to React.FunctionComponent
@see — React.FunctionComponent
@alias — VoidFunctionComponent

2024-08-08 04:57 UTC, al-revenko approved these changes

2024-09-30 18:44 UTC, merged